version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql-
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: mydb
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: node-app
    depends_on:
      - db
    environment:
      DB_HOST: 
      DB_USER: 
      DB_PASSWORD: 
      DB_NAME: mydb
    ports:
      - "3000:3000"
