service: flashcards-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1 

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: flashcards
          method: get
          cors: true
      - http:
          path: flashcards
          method: post
          cors: true
      - http:
          path: flashcards/{id}
          method: put
          cors: true
      - http:
          path: flashcards/{id}
          method: delete
          cors: true

plugins:
  - serverless-offline 

package:
  exclude:
    - node_modules/**
    - .git/**




